// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cities.sql

package database

import (
	"context"
)

const createCity = `-- name: CreateCity :one
INSERT INTO cities (id, name, country, lat, lon)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, country, lat, lon, created_at
`

type CreateCityParams struct {
	ID      int64
	Name    string
	Country string
	Lat     float64
	Lon     float64
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (City, error) {
	row := q.db.QueryRowContext(ctx, createCity,
		arg.ID,
		arg.Name,
		arg.Country,
		arg.Lat,
		arg.Lon,
	)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Country,
		&i.Lat,
		&i.Lon,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCity = `-- name: DeleteCity :exec
DELETE FROM cities
WHERE id = ?
`

func (q *Queries) DeleteCity(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCity, id)
	return err
}
