// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type City struct {
	ID        int64
	Name      string
	Country   string
	Lat       float64
	Lon       float64
	CreatedAt time.Time
}

type WeatherCache struct {
	ID          int64
	CityID      sql.NullInt64
	CityName    sql.NullString
	Country     sql.NullString
	Lat         sql.NullFloat64
	Lon         sql.NullFloat64
	WeatherMain sql.NullString
	WeatherDesc sql.NullString
	WeatherIcon sql.NullString
	Temp        sql.NullFloat64
	FeelsLike   sql.NullFloat64
	TempMin     sql.NullFloat64
	TempMax     sql.NullFloat64
	Humidity    sql.NullInt64
	Pressure    sql.NullInt64
	WindSpeed   sql.NullFloat64
	WindDeg     sql.NullInt64
	WindGust    sql.NullFloat64
	Rain1h      sql.NullFloat64
	Cloudiness  sql.NullInt64
	Visibility  sql.NullInt64
	WeatherTime sql.NullInt64
	FetchedAt   sql.NullInt64
	Timezone    sql.NullInt64
	WeatherID   sql.NullInt64
	SeaLevel    sql.NullInt64
	GroundLevel sql.NullInt64
	Sunrise     sql.NullInt64
	Sunset      sql.NullInt64
}
