// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type City struct {
	ID        int64
	Name      string
	Country   string
	Lat       float64
	Lon       float64
	CreatedAt time.Time
}
